version: "3"

services:
  app:
    build: ./docker/app
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: YourMemo
    volumes:
      - laravel-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8080:80
volumes:
  laravel-db-data:
    driver: local
