version: "3"
services:
  nginx:
    image: nginx:1.17.8-alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/cert-key:/etc/nginx/ssl
  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - db
      - mailhog
    ports:
      - 9000:9000
      - 8001:8001
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      # - ../_docker/xdebug/php.ini:/usr/local/etc/php/php.ini
      # - yarn-cache:/usr/local/share/.cache/yarn/v6
      # - exclude:/var/www/html/node_modules
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=yourmemo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=koseiProgramDev
    volumes:
      - ./yourmemo:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 8080:80
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
